%Facial attactiveness analysis and rating system base on the facial
%landmarks generated by Project-out Cascaded Regression.
s1 = 'Z:\helen\trainset\';
s2 = '.pts';
s3 = '.jpg';
fname = '18467619_1';
fpts = strcat(s1,fname,s2);
fimage = strcat(s1, fname, s3);
mX = zeros(68,1);
mY = zeros(68,1);
mMeanX = zeros(68,1);
mMeanY = zeros(68,1);
mNormedX = zeros(68,1);
mNormedY = zeros(68,1);
fid=fopen(fpts,'r');
fgetl(fid);
fgetl(fid); 
fgetl(fid);
formatSpec = '%f %f';
sizeA = [2 68];
A = fscanf(fid,formatSpec,sizeA);
fclose(fid);
A = A';

%for x-axis
for i = 1:68
    mX(i,1) = A(i,1);
 % fprintf('%g\n',A(i,1));
end

meanOfX = mean(mX);
for i = 1:68
    mMeanX(i,1) = mX(i,1) - meanOfX;
end
meanOfXAfter = mean(mMeanX);

Xnorm = norm(mMeanX);
for i = 1:68
    mNormedX(i,1) = mMeanX(i,1)/Xnorm;
end

%for y-axis
for i = 1:68
    mY(i,1) = A(i,2);
  %Sfprintf('%g\n',A(i,2));
end

meanOfY = mean(mY);
for i = 1:68
    mMeanY(i,1) = mY(i,1) - meanOfY;
end
meanOfYAfter = mean(mMeanY);

Ynorm = norm(mMeanY);
for i = 1:68
    mNormedY(i,1) = mMeanY(i,1)/Ynorm;
end

%normalized coordinates
mXY = [mNormedX',mNormedY'];
mXY = mXY';
%plot landmarks on face
% image = imread(fimage);
% 
% imshow(image)
% 
% hold on
% 
% for i = 1:68
%     plot(A(i,1),A(i,2),'w.', 'MarkerSize', 20);
% end
% 
% hold off